trigger:
  batch: true

pool:
  vmImage: windows-latest

variables:
  solution: DecodeWheaRecord.sln
  buildPlatform: Any CPU

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: $(solution)
    feedsToUse: select

- task: VSBuild@1
  inputs:
    solution: $(solution)
    platform: $(buildPlatform)
    configuration: Debug
    maximumCpuCount: true

- task: VSBuild@1
  inputs:
    solution: $(solution)
    platform: $(buildPlatform)
    configuration: Release
    maximumCpuCount: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: bin/Release
    artifact: DecodeWheaRecord-$(build.SourceVersion)
    publishLocation: pipeline

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: bin/Debug
    artifact: DecodeWheaRecord-$(build.SourceVersion)-dbg
    publishLocation: pipeline
